title: Introduction to Mathematics for Political Science (2019)
url: /imps2019/
logo:
description: Department of Politics, Princeton University
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
   math_engine: mathjax