title: Princeton Politics Math Camp '18
logo:
description: Syllabus and course materials for annual math camp for incoming Politics Ph.D. students at Princeton University.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
