title: Introduction to Mathematics for Political Scientists (2018)
logo:
description: Department of Politics, Princeton University
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
   math_engine: mathjax